/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controller.ClientController;
import javafx.scene.control.Alert;
import javax.swing.JButton;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JTextField;

/**
 *
 * @author Mystogan
 */
public class cadastrarCliente extends javax.swing.JFrame {

    /**
     * Creates new form cadastrarCliente
     */
    public cadastrarCliente() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        campocliente = new javax.swing.JLabel();
        campo_Nome = new javax.swing.JTextField();
        campo_Email = new javax.swing.JTextField();
        campo_Cnpj = new javax.swing.JTextField();
        campo_Endereco = new javax.swing.JTextField();
        campo_Cep = new javax.swing.JTextField();
        campo_Celular = new javax.swing.JTextField();
        campo_Telefone = new javax.swing.JTextField();
        campo_Fax = new javax.swing.JTextField();
        campo_Site = new javax.swing.JTextField();
        Campo_Observacao = new javax.swing.JTextField();
        campo_Razaosc = new javax.swing.JTextField();
        Site = new javax.swing.JLabel();
        Fax = new javax.swing.JLabel();
        Telefone = new javax.swing.JLabel();
        Celular = new javax.swing.JLabel();
        Observacoes = new javax.swing.JLabel();
        nome = new javax.swing.JLabel();
        Email = new javax.swing.JLabel();
        Razaosc = new javax.swing.JLabel();
        cnpj = new javax.swing.JLabel();
        Endereco = new javax.swing.JLabel();
        cep = new javax.swing.JLabel();
        BTN_back = new javax.swing.JButton();
        BTN_send = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        campo_Email1 = new javax.swing.JTextField();
        cep1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(1047, 704));
        setMinimumSize(new java.awt.Dimension(1047, 704));
        setResizable(false);

        campocliente.setFont(new java.awt.Font("Arial Black", 1, 24)); // NOI18N
        campocliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/fotos logo nova/gearlogo iniciof.png"))); // NOI18N
        campocliente.setText("                  Cadastro do Cliente");
        campocliente.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        campo_Celular.setToolTipText("");

        campo_Site.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campo_SiteActionPerformed(evt);
            }
        });

        Campo_Observacao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Campo_ObservacaoActionPerformed(evt);
            }
        });

        Site.setFont(new java.awt.Font("Serif", 1, 12)); // NOI18N
        Site.setText("Site");

        Fax.setFont(new java.awt.Font("Serif", 1, 12)); // NOI18N
        Fax.setText("Fax");

        Telefone.setFont(new java.awt.Font("Serif", 1, 12)); // NOI18N
        Telefone.setText("Telefone");

        Celular.setFont(new java.awt.Font("Serif", 1, 12)); // NOI18N
        Celular.setText("Celular");

        Observacoes.setFont(new java.awt.Font("Serif", 1, 12)); // NOI18N
        Observacoes.setText("Observações");

        nome.setFont(new java.awt.Font("Serif", 1, 12)); // NOI18N
        nome.setText("Nome Fantasia");

        Email.setFont(new java.awt.Font("Serif", 1, 12)); // NOI18N
        Email.setText("E-mail");

        Razaosc.setFont(new java.awt.Font("Serif", 1, 12)); // NOI18N
        Razaosc.setText("Razão Social");

        cnpj.setFont(new java.awt.Font("Serif", 1, 12)); // NOI18N
        cnpj.setText("CNPJ");

        Endereco.setFont(new java.awt.Font("Serif", 1, 12)); // NOI18N
        Endereco.setText("Endereço");

        cep.setFont(new java.awt.Font("Serif", 1, 12)); // NOI18N
        cep.setText("Cep");

        BTN_back.setText("Voltar");
        BTN_back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTN_backActionPerformed(evt);
            }
        });

        BTN_send.setText("Cadastrar");
        BTN_send.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTN_sendActionPerformed(evt);
            }
        });

        jLabel1.setText("* Campo Obrigatorio");

        cep1.setFont(new java.awt.Font("Serif", 1, 12)); // NOI18N
        cep1.setText("CPF");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(BTN_back, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(22, 22, 22)
                                .addComponent(BTN_send, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(27, 27, 27))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(cnpj)
                                        .addComponent(campo_Cnpj, javax.swing.GroupLayout.DEFAULT_SIZE, 202, Short.MAX_VALUE)
                                        .addComponent(Celular)
                                        .addComponent(campo_Celular))
                                    .addGap(51, 51, 51)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(Endereco)
                                        .addComponent(Telefone)
                                        .addComponent(campo_Telefone, javax.swing.GroupLayout.DEFAULT_SIZE, 221, Short.MAX_VALUE)
                                        .addComponent(campo_Endereco))
                                    .addGap(42, 42, 42)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(Fax)
                                        .addComponent(cep)
                                        .addComponent(campo_Cep, javax.swing.GroupLayout.DEFAULT_SIZE, 221, Short.MAX_VALUE)
                                        .addComponent(campo_Fax))
                                    .addGap(39, 39, 39)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(campo_Site, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(Site)
                                        .addComponent(cep1)
                                        .addComponent(campo_Email1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(10, 10, 10)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(Email)
                                        .addComponent(campo_Nome, javax.swing.GroupLayout.PREFERRED_SIZE, 295, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGap(30, 30, 30)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(nome)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(campo_Email, javax.swing.GroupLayout.PREFERRED_SIZE, 296, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(39, 39, 39)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(Razaosc)
                                                .addComponent(campo_Razaosc, javax.swing.GroupLayout.PREFERRED_SIZE, 357, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                            .addComponent(Observacoes)
                            .addComponent(jLabel1)
                            .addComponent(Campo_Observacao, javax.swing.GroupLayout.PREFERRED_SIZE, 1027, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(campocliente, javax.swing.GroupLayout.PREFERRED_SIZE, 1047, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, 0))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(campocliente, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Razaosc)
                    .addComponent(Email)
                    .addComponent(nome))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(campo_Nome, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(campo_Email, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(campo_Razaosc, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cnpj)
                    .addComponent(Endereco)
                    .addComponent(cep)
                    .addComponent(cep1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(campo_Cnpj, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(campo_Endereco, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(campo_Cep, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(campo_Email1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Site)
                    .addComponent(Fax)
                    .addComponent(Telefone)
                    .addComponent(Celular))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(campo_Celular, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(campo_Telefone, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(campo_Fax, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(campo_Site, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Observacoes)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Campo_Observacao, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BTN_back, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BTN_send, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(13, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
      public void setidioma(String idioma) {
        if ("Inglês".equals(idioma)) {
            String Registercliente = "         Register Client", Observacao = "Observation", Celular = "Cellphone", Cep = "Zip", Cnpj = "Cnpj", Email = "Email", Endereco = "Address", Fax = "Fax", Nome = "Name", Razaosc = "Social Nome ", Site = "Site", Telefone = "Phone Number";
            this.Celular.setText(Celular);
            this.cep.setText(Cep);
            this.cnpj.setText(Cnpj);
            this.Email.setText(Email);
            this.Endereco.setText(Endereco);
            this.Fax.setText(Fax);
            this.nome.setText(Nome);
            this.Razaosc.setText(Razaosc);
            this.Site.setText(Site);
            this.Telefone.setText(Telefone);
            this.campocliente.setText(Registercliente);
            this.Telefone.setText(Telefone);
        } else if ("Português Brasil".equals(idioma)) {
            String Observacao = "Observaçao", Celular = "Celular", Cep = "Cep", Cnpj = "Cnpj", Email = "Email", Endereco = "Endereço", Fax = "Fax", Nome = "Nome", Razaosc = "Razão Social", Site = "Site", Telefone = "Telefone Number";
            this.campo_Celular.setText(Celular);
            this.campo_Cep.setText(Cep);
            this.campo_Cnpj.setText(Cnpj);
            this.campo_Email.setText(Email);
            this.campo_Endereco.setText(Endereco);
            this.campo_Fax.setText(Fax);
            this.campo_Celular.setText(Nome);
            this.campo_Razaosc.setText(Razaosc);
            this.campo_Site.setText(Site);
            this.campo_Telefone.setText(Telefone);
        }
    }

    public JButton getBTN_back() {
        return BTN_back;
    }

    public void setBTN_back(JButton BTN_back) {
        this.BTN_back = BTN_back;
    }

    public JButton getBTN_send() {
        return BTN_send;
    }

    public void setBTN_send(JButton BTN_send) {
        this.BTN_send = BTN_send;
    }

    public JTextField getCampo_Observacao() {
        return Campo_Observacao;
    }

    public void setCampo_Observacao(JTextField Campo_Observacao) {
        this.Campo_Observacao = Campo_Observacao;
    }

    public JLabel getCelular() {
        return Celular;
    }

    public void setCelular(JLabel Celular) {
        this.Celular = Celular;
    }

    public JLabel getEmail() {
        return Email;
    }

    public void setEmail(JLabel Email) {
        this.Email = Email;
    }

    public JLabel getEndereco() {
        return Endereco;
    }

    public void setEndereco(JLabel Endereco) {
        this.Endereco = Endereco;
    }

    public JLabel getFax() {
        return Fax;
    }

    public void setFax(JLabel Fax) {
        this.Fax = Fax;
    }

    public JLabel getObservacoes() {
        return Observacoes;
    }

    public void setObservacoes(JLabel Observacoes) {
        this.Observacoes = Observacoes;
    }

    public JLabel getRazaosc() {
        return Razaosc;
    }

    public void setRazaosc(JLabel Razaosc) {
        this.Razaosc = Razaosc;
    }

    public JLabel getSite() {
        return Site;
    }

    public void setSite(JLabel Site) {
        this.Site = Site;
    }

    public JLabel getTelefone() {
        return Telefone;
    }

    public void setTelefone(JLabel Telefone) {
        this.Telefone = Telefone;
    }

    public JTextField getCampo_Celular() {
        return campo_Celular;
    }

    public void setCampo_Celular(JTextField campo_Celular) {
        this.campo_Celular = campo_Celular;
    }

    public JTextField getCampo_Cep() {
        return campo_Cep;
    }

    public void setCampo_Cep(JTextField campo_Cep) {
        this.campo_Cep = campo_Cep;
    }

    public JTextField getCampo_Cnpj() {
        return campo_Cnpj;
    }

    public void setCampo_Cnpj(JTextField campo_Cnpj) {
        this.campo_Cnpj = campo_Cnpj;
    }

    public JTextField getCampo_Email() {
        return campo_Email;
    }

    public void setCampo_Email(JTextField campo_Email) {
        this.campo_Email = campo_Email;
    }

    public JTextField getCampo_Email1() {
        return campo_Email1;
    }

    public void setCampo_Email1(JTextField campo_Email1) {
        this.campo_Email1 = campo_Email1;
    }

    public JTextField getCampo_Endereco() {
        return campo_Endereco;
    }

    public void setCampo_Endereco(JTextField campo_Endereco) {
        this.campo_Endereco = campo_Endereco;
    }

    public JTextField getCampo_Fax() {
        return campo_Fax;
    }

    public void setCampo_Fax(JTextField campo_Fax) {
        this.campo_Fax = campo_Fax;
    }

    public JTextField getCampo_Nome() {
        return campo_Nome;
    }

    public void setCampo_Nome(JTextField campo_Nome) {
        this.campo_Nome = campo_Nome;
    }

    public JTextField getCampo_Razaosc() {
        return campo_Razaosc;
    }

    public void setCampo_Razaosc(JTextField campo_Razaosc) {
        this.campo_Razaosc = campo_Razaosc;
    }

    public JTextField getCampo_Site() {
        return campo_Site;
    }

    public void setCampo_Site(JTextField campo_Site) {
        this.campo_Site = campo_Site;
    }

    public JTextField getCampo_Telefone() {
        return campo_Telefone;
    }

    public void setCampo_Telefone(JTextField campo_Telefone) {
        this.campo_Telefone = campo_Telefone;
    }

    public JLabel getCampocliente() {
        return campocliente;
    }

    public void setCampocliente(JLabel campocliente) {
        this.campocliente = campocliente;
    }

    public JLabel getCep() {
        return cep;
    }

    public void setCep(JLabel cep) {
        this.cep = cep;
    }

    public JLabel getCep1() {
        return cep1;
    }

    public void setCep1(JLabel cep1) {
        this.cep1 = cep1;
    }

    public JLabel getCnpj() {
        return cnpj;
    }

    public void setCnpj(JLabel cnpj) {
        this.cnpj = cnpj;
    }

    public JLabel getjLabel1() {
        return jLabel1;
    }

    public void setjLabel1(JLabel jLabel1) {
        this.jLabel1 = jLabel1;
    }

    public JLabel getNome() {
        return nome;
    }

    public void setNome(JLabel nome) {
        this.nome = nome;
    }

    

    private void campo_SiteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campo_SiteActionPerformed
        // TODO add your handling code here:
    
    }//GEN-LAST:event_campo_SiteActionPerformed

    private void BTN_backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTN_backActionPerformed
        this.dispose();
    }//GEN-LAST:event_BTN_backActionPerformed

    private void Campo_ObservacaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Campo_ObservacaoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Campo_ObservacaoActionPerformed

    private void BTN_sendActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTN_sendActionPerformed
        
        ClientController clientC = new ClientController(this);
        if (clientC.verificaCampo())
        {
            clientC.cadastrarClient();
            this.dispose();
        }
        else{
            JOptionPane.showMessageDialog(null, "deu ruim");
        }
       

    }//GEN-LAST:event_BTN_sendActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(cadastrarCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(cadastrarCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(cadastrarCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(cadastrarCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new cadastrarCliente().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BTN_back;
    private javax.swing.JButton BTN_send;
    private javax.swing.JTextField Campo_Observacao;
    private javax.swing.JLabel Celular;
    private javax.swing.JLabel Email;
    private javax.swing.JLabel Endereco;
    private javax.swing.JLabel Fax;
    private javax.swing.JLabel Observacoes;
    private javax.swing.JLabel Razaosc;
    private javax.swing.JLabel Site;
    private javax.swing.JLabel Telefone;
    private javax.swing.JTextField campo_Celular;
    private javax.swing.JTextField campo_Cep;
    private javax.swing.JTextField campo_Cnpj;
    private javax.swing.JTextField campo_Email;
    private javax.swing.JTextField campo_Email1;
    private javax.swing.JTextField campo_Endereco;
    private javax.swing.JTextField campo_Fax;
    private javax.swing.JTextField campo_Nome;
    private javax.swing.JTextField campo_Razaosc;
    private javax.swing.JTextField campo_Site;
    private javax.swing.JTextField campo_Telefone;
    private javax.swing.JLabel campocliente;
    private javax.swing.JLabel cep;
    private javax.swing.JLabel cep1;
    private javax.swing.JLabel cnpj;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel nome;
    // End of variables declaration//GEN-END:variables
}
