/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controller.PartController;
import controller.PedidoController;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author Mystogan
 */
public class venderPeca extends javax.swing.JFrame {
    static double aux1=0;
    /**
     * Creates new form venderPeca
     */
    
    public venderPeca() {
        initComponents();
        venderPeca.aux1=0;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BTN_send = new javax.swing.JButton();
        BTN_back = new javax.swing.JButton();
        sellPart = new javax.swing.JLabel();
        campo_Nome1 = new javax.swing.JTextField();
        searchclient = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        campo_Nome = new javax.swing.JTextField();
        cpf = new javax.swing.JTextField();
        razao = new javax.swing.JTextField();
        cep1 = new javax.swing.JLabel();
        cep2 = new javax.swing.JLabel();
        cep3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablePeca = new javax.swing.JTable();
        campo_Nome4 = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        searchpart = new javax.swing.JLabel();
        cart = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        carrin = new javax.swing.JTable();
        BTN_back1 = new javax.swing.JButton();
        BTN_back2 = new javax.swing.JButton();
        amount = new javax.swing.JLabel();
        rs = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tablecliente = new javax.swing.JTable();

        BTN_send.setText("Cadastrar");
        BTN_send.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTN_sendActionPerformed(evt);
            }
        });

        BTN_back.setText("Voltar");
        BTN_back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTN_backActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        sellPart.setFont(new java.awt.Font("Arial Black", 1, 24)); // NOI18N
        sellPart.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/fotos logo nova/gearlogo iniciof.png"))); // NOI18N
        sellPart.setText("                Vender Peça");
        sellPart.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        campo_Nome1.setToolTipText("CPF/NAME");

        searchclient.setText("   Buscar Cliente");
        searchclient.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/fotos logo nova/lupa.jpg"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        campo_Nome.setEditable(false);
        campo_Nome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campo_NomeActionPerformed(evt);
            }
        });

        cpf.setEditable(false);

        razao.setEditable(false);
        razao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                razaoActionPerformed(evt);
            }
        });

        cep1.setFont(new java.awt.Font("Serif", 1, 12)); // NOI18N
        cep1.setText("CPF");

        cep2.setFont(new java.awt.Font("Serif", 1, 12)); // NOI18N
        cep2.setText("Nome Fantasia");

        cep3.setFont(new java.awt.Font("Serif", 1, 12)); // NOI18N
        cep3.setText("Razão Social");

        tablePeca.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "", "", ""
            }
        ));
        tablePeca.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablePecaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tablePeca);

        campo_Nome4.setToolTipText("CPF/NAME");

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/fotos logo nova/lupa.jpg"))); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        searchpart.setText("   Buscar Peça");
        searchpart.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        cart.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        cart.setText("Carrrinho");

        carrin.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Título 1", "Título 2", "Título 3"
            }
        ));
        jScrollPane2.setViewportView(carrin);

        BTN_back1.setText("Voltar");
        BTN_back1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTN_back1ActionPerformed(evt);
            }
        });

        BTN_back2.setText("Comprar");
        BTN_back2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTN_back2ActionPerformed(evt);
            }
        });

        amount.setText("Valor Total:");

        rs.setText("R$");

        tablecliente.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "", "", "", ""
            }
        ));
        tablecliente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableclienteMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(tablecliente);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(BTN_back1, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(BTN_back2, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cpf, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cep1))
                        .addGap(46, 46, 46)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(campo_Nome, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cep2))
                        .addGap(46, 46, 46)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cep3)
                            .addComponent(razao, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(searchpart, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, 0)
                                .addComponent(campo_Nome4, javax.swing.GroupLayout.PREFERRED_SIZE, 824, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(searchclient, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, 0)
                                .addComponent(campo_Nome1)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(amount)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(rs))
                    .addComponent(sellPart, javax.swing.GroupLayout.PREFERRED_SIZE, 963, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 948, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 948, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 948, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 83, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(399, 399, 399)
                .addComponent(cart)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(sellPart, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(campo_Nome1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(searchclient, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, 0)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cep1)
                    .addComponent(cep2)
                    .addComponent(cep3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(campo_Nome, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cpf, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(razao, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(campo_Nome4, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(searchpart, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, 0)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cart)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(amount)
                    .addComponent(rs))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BTN_back1, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BTN_back2, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
     public void setidioma(String idioma) {
        if ("Inglês".equals(idioma)) {
            String sellPart = "Sell Parts", searchClient = "Search Client", searchPart = "Search Part", cart = "Cart", amount = "Amount: ";
            this.sellPart.setText(sellPart);
            this.searchpart.setText(searchPart);
            this.searchclient.setText(searchClient);
            this.cart.setText(cart);
            this.amount.setText(amount);
        } else if ("Português Brasil".equals(idioma)) {
            String sellPart = "Vender Peças", searchClient = "Buscar Cliente", searchPart = "Buscar Peça", cart = "Carrinho", amount = "Valor Total: ";
            this.sellPart.setText(sellPart);
            this.searchpart.setText(searchPart);
            this.searchclient.setText(searchClient);
            this.cart.setText(cart);
            this.amount.setText(amount);
        }
    }

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        verificacampo();
       // PedidoController pedido = new PedidoController(this);
        //pedido.buscarCliente();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void campo_NomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campo_NomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campo_NomeActionPerformed

    private void razaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_razaoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_razaoActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        PedidoController pedido = new PedidoController(this);
        pedido.buscarPeca();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void BTN_sendActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTN_sendActionPerformed
       
    }//GEN-LAST:event_BTN_sendActionPerformed

    private void BTN_backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTN_backActionPerformed
        this.dispose();
    }//GEN-LAST:event_BTN_backActionPerformed

    private void BTN_back1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTN_back1ActionPerformed
        this.dispose();
    }//GEN-LAST:event_BTN_back1ActionPerformed

    private void BTN_back2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTN_back2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BTN_back2ActionPerformed

    private void tableclienteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableclienteMouseClicked
    int[] index = tablecliente.getSelectedRows();
    Object[] row = new Object[4];
    String[] lol = new String[4];
    for(int i=0;i<3;i++){     
    row[0] = tablecliente.getValueAt(index[i], 0);
    row[1] = tablecliente.getValueAt(index[i], 1);
    row[2] = tablecliente.getValueAt(index[i], 2);
       cpf.setText(row[0].toString());
        campo_Nome.setText(row[1].toString());
         razao.setText(row[2].toString());
     }                                     
    }//GEN-LAST:event_tableclienteMouseClicked

    private void tablePecaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablePecaMouseClicked
    int[] index = tablePeca.getSelectedRows();
    Object[] prow = new Object[3];
    double test=0; 
    
    TableModel model1 = tablePeca.getModel();
    DefaultTableModel model2 = (DefaultTableModel) carrin.getModel();
    for(int i=0;i<1;i++){     
    prow[0] = model1.getValueAt(index[i], 0);
    prow[1] = model1.getValueAt(index[i], 1);
    prow[2] = model1.getValueAt(index[i], 2);
    venderPeca.aux1+=Double.parseDouble(String.valueOf(prow[2]));
    
    String aux2;
 //   double aux = Double.parseDouble(aux1);
    //test = test + aux;
    aux2 = String.valueOf(venderPeca.aux1);
    model2.addRow(prow);
    
    rs.setText("R$ "+venderPeca.aux1);
      }
    
    }//GEN-LAST:event_tablePecaMouseClicked

    public void verificacampo(){
   String user = "root";
   String password = "";
   String server = "jdbc:mysql://localhost:3306/sofm";
   String driver = "com.mysql.jdbc.Driver";
   try{
       Class.forName(driver);
      Connection con = DriverManager.getConnection(server, user, password);  ;
    Statement st = con.createStatement();
    if(campo_Nome1.getText().isEmpty()){
         ResultSet rs = st.executeQuery("select * from client"); 
         tablecliente.setModel(DbUtils.resultSetToTableModel(rs));
    }else {
         String nomebusca = campo_Nome1.getText();
         ResultSet rs = st.executeQuery("select * from client where nome="+"'"+nomebusca+"'"+";"); 
         tablecliente.setModel(DbUtils.resultSetToTableModel(rs));
    }
   }catch(Exception e){
       JOptionPane.showMessageDialog(null,"Erro"+e.getMessage());
      } 
   
   }
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(venderPeca.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(venderPeca.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(venderPeca.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(venderPeca.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new venderPeca().setVisible(true);
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BTN_back;
    private javax.swing.JButton BTN_back1;
    private javax.swing.JButton BTN_back2;
    private javax.swing.JButton BTN_send;
    private javax.swing.JLabel amount;
    private javax.swing.JTextField campo_Nome;
    private javax.swing.JTextField campo_Nome1;
    private javax.swing.JTextField campo_Nome4;
    private javax.swing.JTable carrin;
    private javax.swing.JLabel cart;
    private javax.swing.JLabel cep1;
    private javax.swing.JLabel cep2;
    private javax.swing.JLabel cep3;
    private javax.swing.JTextField cpf;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextField razao;
    private javax.swing.JLabel rs;
    private javax.swing.JLabel searchclient;
    private javax.swing.JLabel searchpart;
    private javax.swing.JLabel sellPart;
    public javax.swing.JTable tablePeca;
    public javax.swing.JTable tablecliente;
    // End of variables declaration//GEN-END:variables

    public JTable getTablePeca() {
        return tablePeca;
    }

    public void setTablePeca(JTable tablePeca) {
        this.tablePeca = tablePeca;
    }
}
